[package]
name = "elastic_reqwest"
version = "0.20.4"
authors = ["Ashley Mannix <ashleymannix@live.com.au>", "Stephan Buys <stephan.buys@gmail.com>"]
license = "Apache-2.0"
description = "A lightweight implementation of the Elasticsearch API based on reqwest."
documentation = "https://docs.rs/elastic_reqwest/"
repository = "https://github.com/elastic-rs/elastic"
readme = "README.md"

[dependencies]
serde = "~1"
elastic_requests = { version = "~0.20.0", path = "../requests" }
elastic_responses = { version = "~0.20.2", path = "../responses" }
reqwest = { version = "~0.8.0", features = ["unstable"] }
url = "~1"
bytes = "0.4.5"
tokio-core = "~0.1.9"
futures = "~0.1.16"
serde_json = "~1"
quick-error = "~1"

[dev-dependencies]
json_str = "^0.*"
