sudo: required
language: rust
services:
  - docker

matrix:
  include:
    - rust: stable
      env:
        - CHANNEL="stable"
    - rust: nightly
      env:
        - CHANNEL="nightly"
        - KIND="build"
    - rust: nightly
      env:
        - CHANNEL="nightly"
        - KIND="integration"

script: ./ci/travis.sh

notifications:
  email:
    on_success: never
