[package]
name = "elastic_hyper"
version = "0.3.1"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
description = "A lightweight implementation of the Elasticsearch API based on Hyper."
documentation = "https://docs.rs/elastic_types/0.3.1/elastic_hyper/"
repository = "https://github.com/elastic-rs/elastic-hyper"
exclude = [ "samples", "codegen" ]

[features]
default = [ "ssl" ]
ssl = [ "hyper/ssl" ]

[dependencies]
hyper = { version = "~0.9.0", default-features = false }
url = "~1.1.0"

[dev-dependencies]
json_str = "^0.*"
