[package]
name = "elastic_types"
version = "0.5.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "Apache-2.0"
description = "A strongly-typed implementation of Elasticsearch core types and Mapping API."
documentation = "http://kodraus.github.io/rustdoc/elastic_types/"
repository = "https://github.com/elastic-rs/elastic-types"

[features]
nightly = [
	"elastic_date_macros/nightly",
	"elastic_types_macros",
	"serde_macros"
]
nightly-testing = ["nightly"]

[dependencies]
serde = "~0.8.0"
serde_json = "~0.8.0"
chrono = { version = "~0.2.20", features = [ "serde" ]}
geo = "~0.0.7"
geohash = "~0.2.7"
geojson = { version = "~0.4.0", features = [ "with-serde" ] }

serde_macros = { version = "~0.8.0", optional = true }
elastic_date_macros = { version = "*", path = "../macros/date" }
elastic_types_macros = { version = "*", path = "../macros/types", optional = true }

[dev-dependencies]
json_str = "^0.*"
maplit = "^0.*"
