[package]
name = "account-sample"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[features]
nightly = ["elastic/nightly"]

[dependencies]
elastic = { version = "*", path = "../../" }
elastic_derive = { version = "*", path = "../../../derive" }

quick-error = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
