[package]
name = "elastic_bench_raw"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
json_str = { version = "*", features = ["nightly"]}

elastic = { version = "*", path = "../../../", features = ["nightly"] }

lazy_static = "*"
time = "*"
stopwatch = "*"
