[package]
name = "elastic_requests"
version = "0.20.10"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "MIT/Apache-2.0"
description = "Code generated request types for the Elasticsearch REST API."
documentation = "https://docs.rs/elastic_requests/"
repository = "https://github.com/elastic-rs/elastic"
readme = "README.md"

[dependencies]
