[package]
name = "elastic_requests"
version = "0.21.0-pre.1"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
license = "MIT/Apache-2.0"
description = "Code generated request types for the Elasticsearch REST API."
documentation = "https://docs.rs/elastic_requests/"
repository = "https://github.com/elastic-rs/elastic"

[dependencies]
http = "~0.1"